Icinga/icinga-vagrant

icinga2x/manifests/default.pp

icinga2x: Fix missing Graphite packages

---

icinga2x/files/etc/icinga2/demo/bp_cluster.conf
icinga2x/files/etc/icingaweb2/modules/businessprocess/processes/all.conf
icinga2x/manifests/default.pp

Add Business Process service checks

---

icinga2x-influxdb/files/etc/icinga2/grafana-dashboard-icinga2-influxdb.json
icinga2x-influxdb/files/etc/icinga2/influxdb-base-metrics.json
icinga2x-influxdb/files/etc/icinga2/influxdb-icinga2-default.json
icinga2x-influxdb/files/etc/icingaweb2/modules/grafana/config.ini
icinga2x-influxdb/files/usr/local/bin/grafana-setup
icinga2x-influxdb/manifests/default.pp

icinga2x-influxdb: Integrate icingaweb2-module-grafana

---

dev/icinga1x-dev/Vagrantfile
dev/icinga2x-freebsd/Vagrantfile
icinga2x-cluster/Vagrantfile
icinga2x-elastic/Vagrantfile
icinga2x-graylog/Vagrantfile
icinga2x-ha-cluster/Vagrantfile
icinga2x-influxdb/Vagrantfile
icinga2x/Vagrantfile

Vagrant: Explicitly disable updates if vagrant-vbguest plugin is installed

---

modules/profiles/manifests/icinga/icingaweb2.pp

See icinga/icingaweb2-module-elasticsearch#20

icingaweb2-module-elasticsearch: Use git master

---

modules/profiles/templates/icinga/icingaweb2/apache_fpm.conf.erb

Refers to icinga/icingaweb2#3366

Icinga Web 2: Fix basic auth in apache config

---

.puppet/modules/profiles/manifests/dashing/icinga2.pp
.puppet/modules/profiles/templates/dashing/config/icinga2.local.json.erb
standalone/environments/vagrant/manifests/default.pp

Dashing: Use a local configuration file to add Icinga Web 2 listen IP

---

.puppet/hieradata/common.yaml
.puppet/modules/profiles/manifests/base/system.pp
README.md
distributed/environments/vagrant/manifests/default.pp
elastic/environments/vagrant/manifests/default.pp
graylog/environments/vagrant/manifests/default.pp
influxdb/environments/vagrant/manifests/default.pp
standalone/environments/vagrant/manifests/default.pp

Hiera: Allow to configure the Icinga package repository type

---

.puppet/hieradata/common.yaml
.puppet/modules/profiles/manifests/graphite/server.pp

Graphite: Update to 1.1.2

---

.puppet/modules/profiles/manifests/icinga/icingaweb2.pp
.puppet/modules/profiles/templates/icinga/icingaweb2/modules/businessprocess/dashboard.ini.erb
.puppet/modules/profiles/templates/icinga/icingaweb2/modules/cube/dashboard.ini.erb
.puppet/modules/profiles/templates/icinga/icingaweb2/modules/map/dashboard.ini.erb

Use concat(::fragment) to populate dashboard.ini - achievement unlocked :)

Provide Icinga Web 2 dashboards for map, cube, businessprocess

---

.puppet/modules/profiles/manifests/icinga/icingaweb2.pp
graylog/environments/vagrant/manifests/default.pp

Add experimental Graylog module for Icinga Web 2

---

.puppet/modules/profiles/templates/icinga/icinga2/config/demo/maps.conf.erb

As there is support for host & service markers with custom icons in the map module master, I extended the demo config file with some random icons.

Added random icons for map markers

---

.puppet/scripts/shell_provisioner_pre.sh

Update to Puppet 5 as provisioner

---

distributed/environments/vagrant/manifests/default.pp
elastic/environments/vagrant/manifests/default.pp
graylog/environments/vagrant/manifests/default.pp
influxdb/environments/vagrant/manifests/default.pp
standalone/environments/vagrant/manifests/default.pp

Enable director, cube, bp, maps modules in Icinga Web 2 on all standalone boxes

---

.puppet/modules/profiles/manifests/icinga/icingaweb2.pp
standalone/environments/vagrant/manifests/default.pp

Add april, nordlicht, spring themes for Icinga Web 2

---

.puppet/hieradata/common.yaml
.puppet/modules/profiles/templates/grafana/grafana-graphite-setup.erb

Update to Grafana 5.1.0

---

README.md
distributed/Vagrantfile
elastic/Vagrantfile
env/Vagrantfile
graylog/Vagrantfile
influxdb/Vagrantfile
standalone/Vagrantfile

Add requirements and fixes for libvirt NFS for shared folders

---

distributed/Vagrantfile.nodes
elastic/Vagrantfile.nodes
env/Vagrantfile.nodes
graylog/Vagrantfile.nodes
influxdb/Vagrantfile.nodes
standalone/Vagrantfile.nodes

This is available since a couple of months now, so we don't
need to stick with point releases :)

Modify base box to generic bento/centos-7

---

.puppet/scripts/shell_provisioner_pre.sh

- Now it also works with CentOS

If it was CentOS then it was unsupported

---

.puppet/modules/profiles/manifests/icinga/icinga2.pp
.puppet/modules/profiles/manifests/icinga/plugins.pp
.puppet/modules/profiles/templates/icinga/icinga2/config/demo/health.conf.erb
.puppet/modules/profiles/templates/icinga/icinga2/config/demo/hosts.conf.erb

Plugins: Add specific profile and add check_sar_perf integration

---

README.md
centos7-dev/Vagrantfile
centos7-dev/Vagrantfile.nodes
distributed/Vagrantfile.nodes
elastic/Vagrantfile.nodes
graylog/Vagrantfile.nodes
influxdb/Vagrantfile.nodes
standalone/Vagrantfile.nodes
tools/vagrant_helper.rb

Added support for the hyper-v provider for those of us who are unfortunate enough to need it.

Add Hyper-V Support

---

.puppet/modules/profiles/manifests/icinga/icingaweb2.pp
.puppet/modules/profiles/templates/base/env.sh.erb
.puppet/scripts/shell_provisioner_post.sh

... not to have errors like:
icingadirector[32012]: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid()

Upgrade PHP to v7.3
